EXTRA_DIST = htmIndex Healpix Spherematch

noinst_DATA = dummy

dummy:
	make -C htmIndex/src
	make -C Healpix
	make -C Spherematch/src
	touch dummy

clean-local:
	make -C htmIndex clean
	make -C Healpix clean
	make -C Spherematch clean
	rm -f dummy
